{
 "title": "CANedge InfluxDB Writer - Template",
 "time": { "from": "now-1680m", "to": "now-1500m" },
 "templating": {
  "list": [
   {
    "name": "DEVICE",
    "label": "DEVICE",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.measurements(bucket: v.defaultBucket)"
   },
   {
    "name": "SIGNAL",
    "label": "SIGNAL",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.fieldKeys(bucket: v.defaultBucket)"
   }
  ]
 },
 "panels": [
  {
   "title": "${SIGNAL}",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /${DEVICE:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"]  =~ /${SIGNAL:regex}/)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "GPS Position",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /${DEVICE:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Latitude\" or r[\"_field\"] == \"Longitude\")\r\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "Speed (m/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /${DEVICE:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Speed\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Trip distance (m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /${DEVICE:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DistanceTrip\" or r[\"_field\"] == \"DistanceAccuracy\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Attitude",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /${DEVICE:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Roll\" or r[\"_field\"] == \"Pitch\" or r[\"_field\"] == \"Heading\" )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "#Satellites (avg)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /${DEVICE:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Satellites\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Distance (km)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /${DEVICE:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DistanceTotal\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Geofence status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /${DEVICE:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Fence1\" or r[\"_field\"] == \"Fence2\" or r[\"_field\"] == \"Fence3\" or r[\"_field\"] == \"Fence4\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}